completed css-flexbox
josephhparkk/c1022-code-solutions pull request #16
Opened 2022-10-12 23:52 UTC by josephhparkk

https://user-images.githubusercontent.com/113474457/195468377-ddb12424-1560-4d6e-bee1-07590a9ec5bf.mp4

2022-10-12 23:53 UTC, codingcodymiller requested changes
Hey Joseph, your output in the gif does not match the output examples in the exercise, please revise.

2022-10-13 03:02 UTC, josephhparkk commented
![Screen Shot 2022-10-12 at 8 00 24 PM](https://user-images.githubusercontent.com/113474457/195489337-c25054ab-57d0-4f7b-a3ee-7baa2930121f.png)

2022-10-13 15:45 UTC, codingcodymiller requested changes

2022-10-13 15:45 UTC, codingcodymiller commented on css-flexbox/align-items.html
> +      flex-basis: calc(100%/ 3);
This should be on `card-wrapper`

2022-10-13 15:45 UTC, codingcodymiller commented on css-flexbox/justify-content.html
> +      flex-basis: 25%;
This should be on `card-wrapper`

2022-10-13 17:45 UTC, codingcodymiller approved these changes

2022-10-13 18:37 UTC, merged